ARDUINO_DIR  = /usr/share/arduino
TARGET       = fermagent
ARDUINO_LIBS = Wire Wire/utility OneWire SD SoftwareSerial
BOARD_TAG    = uno
ARDUINO_PORT = /dev/ttyACM0
include /usr/share/arduino/Arduino.mk

