ARDUINO_DIR  = /usr/share/arduino
TARGET       = fermagent
USER_LIB_PATH = ./libraries
ARDUINO_LIBS = Wire Wire/utility OneWire SD SoftwareSerial  RTClib RCSwitch DallasTemperature
BOARD_TAG    = uno
ARDUINO_PORT = /dev/ttyACM0
include /usr/share/arduino/Arduino.mk

